# GitHub Actions Workflow for CI/CD
name: CI/CD Pipeline

on:
  push:
    branches: [ master, deployment/* ]
  pull_request:
    branches: [ master ]

env:
  NODE_VERSION: '18'
  BUN_VERSION: '1.0.0'

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ env.BUN_VERSION }}
        
    - name: Install dependencies
      run: bun install
      
    - name: Run linting
      run: bun run lint
      
    - name: Type check
      run: bun run type-check
      
    - name: Build application
      run: bun run build
      
    - name: Run tests
      run: bun run test || echo "Tests not implemented yet"

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ env.BUN_VERSION }}
        
    - name: Install dependencies
      run: bun install
      
    - name: Run security audit
      run: bun audit
      
    - name: Run Snyk security scan
      uses: snyk/actions/node@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  deploy-vercel:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/deployment/vercel'
    needs: [test, security]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ env.BUN_VERSION }}
        
    - name: Install dependencies
      run: bun install
      
    - name: Build application
      run: bun run build
      
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod'

  deploy-netlify:
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/deployment/netlify'
    needs: [test, security]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ env.BUN_VERSION }}
        
    - name: Install dependencies
      run: bun install
      
    - name: Build application
      run: bun run build
      
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.2
      with:
        publish-dir: '.next'
        production-branch: deployment/netlify
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/deployment/docker' || github.ref == 'refs/heads/deployment/aws' || github.ref == 'refs/heads/deployment/azure'
    needs: [test, security]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/esg-pathfinder
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [test, security]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Generate changelog
      id: changelog
      run: |
        # Generate changelog since last tag
        if [ $(git tag -l | wc -l) -gt 0 ]; then
          LAST_TAG=$(git describe --tags --abbrev=0)
          CHANGELOG=$(git log --pretty=format:"- %s" $LAST_TAG..HEAD)
        else
          CHANGELOG=$(git log --pretty=format:"- %s")
        fi
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: ESG Pathfinder v${{ github.run_number }}
        body: |
          ## Changes
          ${{ steps.changelog.outputs.changelog }}
          
          ## Deployment Options
          - 🌟 Vercel: `deployment/vercel` branch
          - 🌊 Netlify: `deployment/netlify` branch
          - 🚂 Railway: `deployment/railway` branch
          - 🐳 Docker: `deployment/docker` branch
          - ☁️ AWS: `deployment/aws` branch
          - 🔷 Azure: `deployment/azure` branch
          
          ## Quick Start
          1. Choose your deployment platform
          2. Switch to the corresponding branch
          3. Follow the platform-specific deployment guide
          4. Deploy your ESG compliance platform!
        draft: false
        prerelease: false